### ISSUE TITLE
LIFX app discovers and controlls lamps; MaxLIFX doesn't anymore

### ISSUE THREAD

**Issue by nfsmaster208** [stringandstickytape/MaxLifx#2]
Unfortunately, I switched my LIFX lamps (four) to a different network entirely, and the lamps will not show up in MaxLifx anymore. They show up and are lightning fast in the LIFX app, but not in MaxLifx. Perhaps there is a difference in how the LIFX Universal Windows app connects to the lamps?

I suppose maybe it has something to do with the LIFX Cloud, but it's really hard to say.

Another Reddit user mentioned that he encountered the same issue, where his lamps show up in the LIFX official app, but not in MaxLifx.

I have been using this program since day one. Would you **please** see if there is anything that can be done for those of us who are having this trouble? Unfortunately, it will be impractical for me to try to go back to the configuration I had before, and I don't want to be without MaxLifx!

Thank you!

**Comment by NobleBrutus** [comment]
Sorry to necro, but is there any fix for this? Same problem - bulbs show in LifX app but not MaxLifX on Windows 10.

**Comment by nfsmaster208** [comment]
Did you try closing the LIFX program control completely before running MAX
LIFX?

**Comment by NobleBrutus** [comment]
Thanks for the suggestion, I did but to no avail.

However I since found the LifXLAN package for Python and have used that to create a simple program for the same purpose.

I discovered that for some reason my Windows 10 likes using the Global broadcast address (255.255.255.255) rather than the local one (which apparently other Win10's like?). So that might have been the issue.
